### ISSUE TITLE
image size in css file

### ISSUE THREAD

**Issue by undercloud** [adam-lynch/gulp-image-data-uri#3]
```CSS
.icon {
  width: 32px;
  height:32px;
}
```

**Comment by adam-lynch** [comment]
Why?

**Comment by undercloud** [comment]
images in queue may have diffrent size

**Comment by undercloud** [comment]
plese check my commits!

**Comment by adam-lynch** [comment]
>images in queue may have diffrent size

But setting the `width` & `height` has no effect on the `background-image`'s size?

---

>plese check my commits!

What are you talking about? :smile:

**Comment by undercloud** [comment]
https://github.com/undercloud/gulp-image-data-uri/commit/f319a8a9aec874c5a719e6ad1b4dce2996d06aea

**Comment by undercloud** [comment]
gulp.spritesmith insert size in css https://github.com/twolfson/gulp.spritesmith/blob/master/docs/example.png

**Comment by adam-lynch** [comment]
Ah ok I get what you're doing now. This module is just a simple wrapper of https://github.com/heldr/datauri though. This should be supported that itself. Could you create an issue there please? :smile:

**Comment by undercloud** [comment]
I found issue https://github.com/heldr/datauri/issues/11, without reply

**Comment by undercloud** [comment]
how to be?

**Comment by adam-lynch** [comment]
I think you should comment there and try to get them to do it. Or create a
pull-request for them.


Regards,
Adam Lynch
