### ISSUE TITLE
Allow creation of placeholder selectors in SASS, e.g. %classname

### ISSUE THREAD

**Issue by davidpauljunior** [adam-lynch/gulp-image-data-uri#5]
It would be great if there was a way to output placeholder selectors as well as, or instead of classes so that they can be extended (`@extend`).
I've tried the custom class but you end up with `.%classname` whereas I'd like to replace the `.` with a `%`, e.g. `%classname`.

**Comment by adam-lynch** [comment]
Closing because the custom template option solves this :smile:
