### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by kenanmalak** [adam-lynch/gulp-image-data-uri#6]
I am getting 
git fetch -a origin (git://github.com/adam-lynch/datauri.template.git) fatal: unable to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/adam-lynch/datauri.template.git) github.com[0: 192.30.252.131]: errno=Operation timed out
npm WARN install Couldn't install optional dependency: Command failed: git fetch -a origin
npm WARN install fatal: unable to connect to github.com:
npm WARN install github.com[0: 192.30.252.131]: errno=Operation timed out

**Comment by adam-lynch** [comment]
Sounds like a problem with your connection? You should be installing from npm anyway. `npm i --save gulp-image-data-uri`. Correct me if I'm wrong.
