### ISSUE TITLE
Error trying to compile

### ISSUE THREAD

**Issue by aventic** [adam-lynch/gulp-image-data-uri#7]
I'm getting this error: 

    return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                    ^
    Error: ENOENT: no such file or directory, open 'D:\git\Base\template.css'

trying to compile with:

    gulp.task('datauri', function () {
	    return gulp.src(path.src.graphic)
		    .pipe(datauri())
		    .pipe(concat('_base64.scss'))
		    .on('error', handleError)
		    .pipe(gulp.dest(path.dest.graphic));
    });

If I create such file template.css I can indeed compile, but thats not the point?!

**Comment by adam-lynch** [comment]
Thanks for pointing this out 👍. It was a bug and it's now fixed (version 1.2.2 is published).
